### ISSUE TITLE
plan to migrate IL data

### ISSUE THREAD

**Issue by fgregg** [openstates/meta#22]
DataMade is running an OCD endpoint where we are already serving some data for cities. I'd like to add Illinois data to this endpoint until openstates makes an OCD endpoint available.

Ideally, when openstates API comes on line, the ocd ids for IL objects would be the same as what we had at our endpoint. 

If DataMade writes a script to export and import data for particular legislature, then this would seem pretty straightforward. Assuming that happens, is this something that y'all would be open to?

**Comment by jamesturk** [comment]
Thinking through what this will take:

We'll be scraping IL data well before we have the API up, so we'd have to drop that data and replace it w/ the datamade data.  I don't think that'd be a problem unless we had done manual fixes (but that seems unlikely since manual fixes will probably be on billy side until we have beta API ready).

So in general we should be alright doing this.

**Comment by jamesturk** [comment]
we've been serving IL data in the new API for a while now, so closing this one

**Comment by fgregg** [comment]
awesome!

**Comment by jamesturk** [comment]
> Jesse Mortenson commented in Jira:

Does it makes sense to assign this toRylie Johnsonas the last remaining subtask is “actually do the matching in all states” ?

**Comment by jamesturk** [comment]
> James Turk commented in Jira:

👍
