### ISSUE TITLE
General API v2 Format

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#28]
There are a lot of good reasons not to re-invent the wheel here.  The Open Civic Data models are a lot more relational, so intelligent "related resource" behavior would be useful.

We'll be using Django (https://github.com/opencivicdata/python-opencivicdata-django) so it is likely we'll wind up using django-rest-framework as it is essentially best-in-class at this point and comes with some nice features we could certainly benefit from.

* The openstates/ocd-jsonapi repo has some work in this direction that uses the JSON API specification.  If we go the JSON API route it is a solid foundation to build upon
* GraphQL could also be incredibly powerful here, but we'd need to look at performance, etc.  In this case we'd most likely use [graphene](https://github.com/graphql-python/graphene/), so we'd need to evaluate stability, etc.

**Comment by jamesturk** [comment]
see https://github.com/openstates/meta/issues/21 for comment on GraphQL approach

**Comment by jamesturk** [comment]
A bit of an update:

The biggest obstacle to a GraphQL API is going to be the maturity of the tooling.  Graphene seems to be the closest thing to a mature solution that works w/ Open Civic Data models & seems fairly stable, but in testing I was having some performance issues that I hadn't been able to resolve.

I just came across: https://yacine.org/2017/02/27/graphqlgraphene-sqlalchemy-and-the-n1-problem/ which is probably worth a closer read to be applied to Django if possible.

graphene-django might have some bugs that make its use less-than-desirable right now: https://github.com/graphql-python/graphene-django/issues/197
https://github.com/graphql-python/graphene-django/issues/179

These could probably be overcome, but it does raise questions about the maturity and given the number of users of the API and our limited resources (i.e. writing our own custom GraphQL implementation isn't at all practical) we might want to opt for something more tried & true.

To that end I've revived some old work as an experiment: https://github.com/openstates/ocd-jsonapi

I think with some thoughtful application of includes, etc. a lot of the common cases (pre-resolving legislators when looking at a vote/etc.) could be made possible via JSON API.  This might also prove to be an easier stepping stone from API v1 for people.  The tooling is also a bit more mature.

**Comment by estaub** [comment]
Without knowing the details of what you ran into, I'm going out on a limb... 

I wouldn't give up on graphql quite yet; just because your first implementation is slow doesn't mean it's hard to get to a fast one.  If you are running into the query explosion problem in the article you referenced, I have that particular arrow stuck in my forehead, too, from my first pass.  Any efficient graphql server implementation has to either avoid the "query explosion" problem by batching up queries, or carefully construct the top-level queries in the schema so it won't happen (I can explain if needed).  If you haven't already, I'd strongly encourage that you check out the graphene dataloader: http://docs.graphene-python.org/en/latest/execution/dataloader/.  

While I haven't used it myself yet in JavaScript, dataloader seems to be the standard approach across different implementations and languages.  I don't need it so much (though I may move to it) because since I'm doing an app, not a general-purpose API, I can do SQL joining and tailoring for specific, well-scoped top-level queries.

Given how mainly-immutable the OpenStates data is, you might also consider caching of a lot of the data at a time-scale beyond the individual request (apart from using dataloader).

**Comment by jamesturk** [comment]
we've all but settled on a GraphQL approach, there'll be a post about this in December w/ a testable endpoint w/ a hopeful beta release in January
