### ISSUE TITLE
Should API v2 contain historical data?

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#30]
A fresh start is nice for a few reasons: more consistency, less work, smaller database/faster queries.

We should look at who is using historical data via the API and figure out if bulk data better serves their needs.  Either way we'll at least have a complete set of 2017 data, just unclear if we'd backfill prior sessions or not.

**Comment by estaub** [comment]
It's also important to consider what the ongoing policy will be regarding "historical" data, and where the cutoff between "historical" and "current" is.  

FWIW... as long as bulk is available for older stuff, I'm personally ok.  But for others who aren't maintaining a replica db, it may be important that all votes for the most recent (or current) term be accessible by API, because these have high information value in the next election, in considering the record of incumbents seeking reelection.  This can be up to four years.

**Comment by jamesturk** [comment]
Good point- I have no desire for us to delete historical bill/vote data
once it exists in the API.

That is to say, 2017 data will be available at least until v3. And I'd
guess probably longer as we're less likely to change the underlying
storage, necessitating such a decision to be made again.
